### ISSUE TITLE
Getting a java.lang.NoSuchFieldError: SSL_MAX_RECORD_LENGTH

### ISSUE THREAD

**Issue by esneider** [lightningj-org/lightningj#32]
### Subject of the issue
After initializing the API using the constructor that takes a manually built `SslContext`, when trying to call any method, I get the exception `java.lang.NoSuchFieldError: SSL_MAX_RECORD_LENGTH`

According to https://github.com/grpc/grpc-java/issues/3989 it's due to the version of netty-tcnative-boringssl-static (a grpc dependency).

Grpc upgraded the dependency and solved this issue at version 1.13.1. However, lightningj is using grpc version 1.7.0.

Would you consider upgrading grpc to a newer version?

### Your environment
* version of lightningj: `0.6.0-Beta`
* version and vendor of JDK: `openjdk version "1.8.0_111"`
* your operating systems: `Debian 4.9.110-3+deb9u2`

### Steps to reproduce
```
final SslContext sslContext = GrpcSslContexts
        .configure(SslContextBuilder.forClient(), SslProvider.OPENSSL)
        .trustManager(new ByteArrayInputStream(sslCertString.getBytes()))
        .build();

final SynchronousLndAPI api = new SynchronousLndAPI(host, port, sslContext, () -> hexMacaroon);

api.decodePayReq(invoice);
```

### Expected behaviour
Get the decoded invoice.

### Actual behaviour

```
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
	at org.lightningj.lnd.proto.LightningGrpc$LightningBlockingStub.decodePayReq(LightningGrpc.java:2922)
	at org.lightningj.lnd.wrapper.SynchronousLndAPI.decodePayReq(SynchronousLndAPI.java:1311)
	... 65 common frames omitted
Caused by: io.netty.channel.ChannelPipelineException: io.grpc.netty.ProtocolNegotiators$TlsNegotiator$1.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:626)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:287)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249)
	at io.grpc.netty.ProtocolNegotiators$AbstractBufferingHandler.channelRegistered(ProtocolNegotiators.java:433)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:128)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1332)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:829)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:513)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 common frames omitted
Caused by: java.lang.NoSuchFieldError: SSL_MAX_RECORD_LENGTH
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.<clinit>(ReferenceCountedOpenSslEngine.java:129)
	at io.netty.handler.ssl.OpenSslContext.newEngine0(OpenSslContext.java:49)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine(ReferenceCountedOpenSslContext.java:378)
	at io.grpc.netty.ProtocolNegotiators$TlsNegotiator$1.handlerAdded(ProtocolNegotiators.java:306)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
	... 19 common frames omitted
```

**Comment by herrvendil** [comment]
Hi

I will try to update to latest of GRPC and check that all test and integration tests still goes through. I will then generate a new release that we can try to see if it fixes the problem. Maybe I will have it ready in a couple of days.

Regards
Philip Vendil

**Comment by esneider** [comment]
Thank you!

**Comment by herrvendil** [comment]
Hi I have now created a new release 0.6.1-Beta-u1 that contains grpc 1.21.0. Do you have the possiblity to test if this version solves your problem?

**Comment by esneider** [comment]
It worked! Thanks
