### ISSUE TITLE
invalid pub key while request openChannel

### ISSUE THREAD

**Issue by cheul123a** [lightningj-org/lightningj#70]
### Subject of the issue
request openchannel return invalid pub key

### Your environment
* version of lightningj: 0.14.2-Beta
* version and vendor of JDK: jdk 1.8
* your operationg systems.: windows 10

### Steps to reproduce
```
 OpenChannelRequest openChannelRequest = new OpenChannelRequest();
  String key = "0304aa0eb12a5d1cd8b3d204f1bba09fd205b1046d6edfe49e41bb8ff65cbff050";
  openChannelRequest.setNodePubkey(key.getBytes());
  openChannelRequest.setLocalFundingAmount(40000);
  openChannelRequest.setPushSat(25000);
  openChannelRequest.setSatPerByte(0);

  lndAPI.openChannel(openChannelRequest);
```

### Expected behaviour
channel opend and return channel id

### Actual behaviour
```
Caused by: org.lightningj.lnd.wrapper.ServerSideException: UNKNOWN: invalid pub key length 133
	at org.lightningj.lnd.wrapper.StatusExceptionWrapper.wrap(StatusExceptionWrapper.java:75)
	at org.lightningj.lnd.wrapper.SynchronousLndAPI.openChannel(SynchronousLndAPI.java:127)
	at com.blockware.lnrestapi.domain.channel.service.ChannelService.test(ChannelService.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 32 common frames omitted
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: invalid pub key length 133
	at io.grpc.Status.asRuntimeException(Status.java:535)
	at io.grpc.stub.ClientCalls$BlockingResponseStream.hasNext(ClientCalls.java:648)
	at org.lightningj.lnd.wrapper.SynchronousAPI.processRepeatableResponse(SynchronousAPI.java:94)
	at org.lightningj.lnd.wrapper.SynchronousLndAPI.openChannel(SynchronousLndAPI.java:122)
	... 40 common frames omitted
```

**Comment by Mta78** [comment]
So do you manage to solve this error ? I'm actually getting the same error, with a invalid length of 66 instead of 133.
